#!/usr/bin/env bash

# Tencent is pleased to support the open source community by making TubeMQ available.
#
# Copyright (C) 2012-2019 Tencent. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use
# this file except in compliance with the License. You may obtain a copy of the
# License at
#
# https://opensource.org/licenses/Apache-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.

unset LANG
unset LC_CTYPE

version=$1
outputDirectory=$2

mkdir -p "$outputDirectory/com/tencent/tubemq/server/common"
cat >"$outputDirectory/com/tencent/tubemq/server/common/TubeServerVersion.java" <<EOF
/*
 * Generated by src/saveServerVersion.sh
 */
package com.tencent.tubemq.server.common;

public class TubeServerVersion {
    public static final String BROKER_VERSION = "$version";
}
EOF

