@rem Tencent is pleased to support the open source community by making TubeMQ available.
@rem
@rem Copyright (C) 2012-2019 Tencent. All Rights Reserved.
@rem
@rem Licensed under the Apache License, Version 2.0 (the "License"); you may not use
@rem this file except in compliance with the License. You may obtain a copy of the
@rem License at
@rem
@rem https://opensource.org/licenses/Apache-2.0
@rem
@rem Unless required by applicable law or agreed to in writing, software
@rem distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
@rem WARRANTIES OF ANY KIND, either express or implied.  See the License for the
@rem specific language governing permissions and limitations under the License.
@rem

@echo off
set version=%1
set outputDirectory=%2

md %outputDirectory%\com\tencent\tubemq\client\common
set TubeClientVersion=%outputDirectory%\com\tencent\tubemq\client\common\TubeClientVersion.java"

echo /* > %TubeClientVersion%
echo  * Generated by src/saveClientVersion.cmd>> %TubeClientVersion%
echo  */>> %TubeClientVersion%
echo package com.tencent.tubemq.client.common;>> %TubeClientVersion%
echo,>> %TubeClientVersion%
echo public class TubeClientVersion {>> %TubeClientVersion%
echo     public static final String CONSUMER_VERSION = "%version%";>> %TubeClientVersion%
echo     public static final String PRODUCER_VERSION = "%version%";>> %TubeClientVersion%
echo } >> %TubeClientVersion%

